#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_dream_tile = env_modules.Clone()

# Godot source files
env_dream_tile.add_source_files(env.modules_sources, "*.cpp")
